# Site settings
title: SLKone
email: hello@slone.com
description: SLKone is a bespoke management consulting firm bridging Strategy, Leadership, and Knowledge to build lasting solutions.
baseurl: ""
url: "https://staging.slkone.com"
github_username: SLKone

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

plugins: [jekyll-paginate]
paginate: 9
paginate_path: "insights/page:num/" ##"page:num"

# Collections
collections:
  insights:
    output: true
  services:
    output: true
  sub-services:
    output: true
  careers:
    output: true
  case-studies:
    output: true
  expertise:
    output: true
  industries:
    output: true
  sub-industries:
    output: true
  team-members:
    output: true

# Defaults
defaults:
  - scope:
      path: "/services/"
      type: "services"
      permalink: "/:title/"
    values:
      layout: "service"
      permalink: "/:title/"
  - scope:
      path: "/insights/"
      type: "insights"
      permalink: "/:title/"
    values:
      layout: "post"
      permalink: "/:title/"
  - scope:
      path: "/sub-services/"
      type: "sub-services"
      permalink: "/:title/"
    values:
      layout: "sub-service"
      permalink: "/:parent/:title/"
  - scope:
      path: "/industries/"
      type: "industries"
      permalink: "/:title/"
    values:
      layout: "industry"
      permalink: "/:title/"
  - scope:
      path: "/sub-industries/"
      type: "sub-industries"
      permalink: "/:title/"
    values:
      layout: "sub-industry"
      permalink: "/:parent/:title/"
  - scope:
      path: "/careers/"
      type: "careers"
    values:
      layout: "career"
      permalink: "/:title/"
  - scope:
      path: "/case-studies/"
      type: "case_studies"
    values:
      layout: "case_study"
      permalink: "/:title/"
  - scope:
      path: "/expertise/"
      type: "expertise"
    values:
      layout: "expertise"
      permalink: "/:title/"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - assets/css/tailwind.css
  - postcss.config.js

# Sass settings
sass:
  style: compressed

# Include processed CSS
include:
  - assets/css/main.css